# Generated by Django 3.1 on 2022-01-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20220109_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute_value_id',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attribute_value_id',
            field=models.ManyToManyField(to='ecommerce.AttributeValue'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_image_name',
            field=models.ImageField(upload_to='product/images'),
        ),
    ]
